import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next Auth',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='bg-gray-800 min-h-screen'>
          <nav className="bg-white border-gray-200 dark:bg-gray-900">
            <div className="max-w-7xl flex flex-wrap items-center justify-between mx-auto p-4">
              <a href="#" className="flex items-center dark:text-white">
                Logo
              </a>
            </div>
          </nav>

          <Toaster />

          <main>
            <div className='max-w-7xl mx-auto'>
              {children}
            </div>
          </main>
            
        </div>
        
      </body>
    </html>
  )
}
